steps:
  - name: gcr.io/cloud-builders/docker
    id: build-app
    args:
      - build
      - --file=deploy/app/Dockerfile
      - --tag=${_IMAGE}
      - .

images:
  - ${_IMAGE}

substitutions:
  _LOCATION: us-central1
  _REPO_NAME: gemmaglot-app
  _SERVICE_NAME: gemmaglot-app
  _IMAGE: ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}

options:
  dynamicSubstitutions: true
